-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS USERS.CLIENT(
    ID uuid PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE ,
    PASSWORD_HASH VARCHAR(255) NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USERS.AUTH(
    ID uuid PRIMARY KEY ,
    USER_ID uuid NOT NULL REFERENCES USERS.CLIENT(ID) ON DELETE CASCADE ,
    TOKEN TEXT NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE USERS.CLIENT;
DROP TABLE USERS.AUTH;
-- +goose StatementEnd
